### PR TITLE
Update Readme for API reference

### PR DESCRIPTION
**Pull request by dougwein**
Updating the readme to point to the problem statement on Topcoder for details on the submission API.

### CODE REVIEW

**Comment by peterhaglich** [comment]
Looks right but I think it’s missing a word or two.

**Comment by peterhaglich** [comment]
Am on mobile otherwise I’d edit and commit

**Comment by peterhaglich** [comment]
I made the change I suggested.  @dougwein do we need anything else?

**Comment by dougwein** [comment]
@peterhaglich nothing else, just the API reference was needed.

**Comment by dougwein** [comment]
@peterhaglich a few additional items suggested by catskills:

Need to add these additional links:
Leader board: http://community.topcoder.com/longcontest/?module=ViewStandings&rd=17231
Submission Process: https://solutions.topcoder.com/mercury-challenge/submission

**Comment by peterhaglich** [comment]
Looks good, Doug

**Pull request merged**
